name = "meizhan"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"
pages_build_output_dir = "./dist"

kv_namespaces = [
	{ binding = "MfaStatus", id = "95cfe18dae5a4f7a9b06d3f375d7abd2" },
	{ binding = "LogtoAccessToken", id = "57362cdd50314838bf526bed3f3c6b2a" },
	{ binding = "UsernameChangeTimelimit", id = "2a7ac3d8c54c4c4ab45ede96db61cd54" }
]

[vars]
VITE_LOGTO_ENDPOINT = "https://auth.sh.creativone.cn"
VITE_LOGTO_APPID = "6aa8l1189gr6fwhkulr4h"
VITE_LOGTO_CORE_RESOURCE = "https://default.logto.app/api"
VITE_LOGTO_RESOURCES = "[\"https://default.logto.app/api\"]"
VITE_ROOT = "https://meizhan.4399876.xyz"
VITE_LOGTO_ACCOUNT_URL = "https://auth.sh.creativone.cn"
VITE_SUPPORT_EMAIL = "support@creativone.cn"
VITE_LEGAL_URL = "https://sh.creativone.cn/legal"
LOGTO_DOMAIN = "https://auth.sh.creativone.cn"
LOGTO_DEFAULT_RESOURCE = "https://default.logto.app/api"
VITE_COMMIT_HASH=71c9298a1ca94a21c37548b06628b203555b5052
AVATAR_API = ""
ENABLE_NSFW_CHECK = 0

[placement]
mode = "smart"
